#version: '3.8'

services:
  n8n:
    image: n8nio/n8n:2.0.2
    container_name: exCal-n8n
    restart: always
    ports:
      - "5678:5678"
    env_file:
      - .env
    volumes:
    # Damit landen die n8n-Dateien direkt in deinem Projektordner unter /n8n_data
    - ./n8n_data:/home/node/.n8n
    # Optional: Falls du lokale Dateien in n8n verarbeiten willst:
    - ./local_files:/files
    